hmrc/vat-return-period-frontend

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/filters/ServiceFilters.scala
app/config/filters/WhitelistFilter.scala
build.sbt
conf/application.conf
test/config/filters/WhitelistFilterSpec.scala
test/mocks/MockConfig.scala

Merge after https://github.com/hmrc/vat-return-period-frontend/pull/2
Here are the corresponding app-config-prs: 
BASE: https://github.com/hmrc/app-config-base/pull/2495
QA: https://github.com/hmrc/app-config-qa/pull/4597
PROD: https://github.com/hmrc/app-config-production/pull/4380

BTAT-6576 Added whitelisting config

---

README.md
app/config/FrontendAppConfig.scala
app/views/govuk_wrapper.scala.html
app/views/hello_world.scala.html
test/mocks/MockConfig.scala

* [ x] Branch is rebased with master

BTAT-6895-rebase - Added welsh language toggle to template

---

README.md
app/config/FrontendAppConfig.scala
app/controllers/LanguageController.scala
app/views/govuk_wrapper.scala.html
app/views/hello_world.scala.html
conf/app.routes
conf/application.conf
conf/messages.cy
test/controllers/LanguageControllerSpec.scala
test/mocks/MockConfig.scala

* [ x] Branch is rebased with master
* [x ] Added Unit Tests for changed functionality

BTAT-6896-new - Added language controller and welsh messages

---

app/models/returnFrequency/ReturnPeriod.scala
build.sbt
test/assets/ReturnPeriodTestConstants.scala
test/models/returnFrequency/ReturnPeriodSpec.scala

[BTAT-6945] - added annual return period to model

---

app/views/returnFrequency/chooseDates.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala
test/views/returnFrequency/ChooseDatesViewSpec.scala

[BTAT-6947] - updated chooseDates page for AA

---

README.md

[BTAT-6947-readme] - added new line to readme to trigger build

---

app/controllers/ChangeClientController.scala
test/controllers/ChangeClientControllerSpec.scala

Updated change client handoff URL

---

app/controllers/returnFrequency/ConfirmVatDatesController.scala
app/views/returnFrequency/confirm_dates.scala.html
build.sbt
conf/messages
conf/messages.cy
it/pages/ConfirmVatDatesControllerISpec.scala
test/assets/messages/ReturnFrequencyMessages.scala
test/views/returnFrequency/ChooseDatesViewSpec.scala
test/views/returnFrequency/ConfirmDatesViewSpec.scala

* [ x] Branch is rebased with master
* [ x] Added Unit Tests for changed functionality
* [x ] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum

BTAT 6948 - Update confirm dates page

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/govuk_wrapper.scala.html
build.sbt
conf/application.conf

BTAT-7033 Removed ally report link

---

conf/messages.cy

* [x ] Branch is rebased with master

BTAT-7064 - Updated the meesages.cy file

---

app/views/govuk_wrapper.scala.html
app/views/main_template.scala.html
conf/messages
conf/messages.cy
test/views/GovUkWrapperSpec.scala

[BTAT-7168] Added sign out link to pages

---

app/views/govuk_wrapper.scala.html
build.sbt
test/views/GovUkWrapperSpec.scala

BTAT-7136 Removed logo

---

app/config/FrontendAppConfig.scala
app/views/govuk_wrapper.scala.html
conf/messages
conf/messages.cy
test/mocks/MockConfig.scala
test/views/GovUkWrapperSpec.scala

Added BETA phase banner

---

app/views/govuk_wrapper.scala.html
project/plugins.sbt
public/palette.css

* [ X] Branch is rebased with master
* [ X] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ X] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)

BTAT-7143 - Fix for language toggle comes first

---

build.sbt
project/build.properties
project/plugins.sbt

Minor dependency updates

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/controllers/returnFrequency/ChangeReturnFrequencyConfirmation.scala
app/models/circumstanceInfo/CircumstanceDetails.scala
app/views/returnFrequency/change_return_frequency_confirmation.scala.html
build.sbt
conf/application.conf
conf/messages
conf/messages.cy
it/stubs/VatSubscriptionStub.scala
test/assets/CircumstanceDetailsTestConstants.scala
test/assets/messages/ReturnFrequencyMessages.scala
test/controllers/returnFrequency/ChangeReturnFrequencyConfirmationSpec.scala
test/views/returnFrequency/ChangeReturnFrequencyConfirmationViewSpec.scala

[BTAT-7560] - different content for user with digital preference and verified email

---

project/plugins.sbt
public/css/palette.css

BTAT-7638 Updated confirmation h1 box colour

---

app/views/templates/inputs/radioGroup.scala.html
build.sbt
test/views/templates/inputs/RadioGroupTemplateSpec.scala

[BTAT-7775] - corrected error format

---

conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala

* [ X] Branch is rebased with master
* [ X] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ X] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)

BTAT-7783 Content changed for return frequency

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/returnFrequency/change_return_frequency_confirmation.scala.html
app/views/templates/updateClient.scala.html
build.sbt
conf/application.conf
conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala
test/base/BaseSpec.scala
test/views/returnFrequency/ChangeReturnFrequencyConfirmationViewSpec.scala

Please merge this PR also: https://github.com/hmrc/app-config-production/pull/6868

BTAT-7786 Adding feature and content for bulk agent paper update

---

app/controllers/SignOutController.scala
app/controllers/predicates/AuthPredicate.scala
app/controllers/returnFrequency/ChangeReturnFrequencyConfirmation.scala
app/controllers/returnFrequency/ConfirmVatDatesController.scala
conf/application.conf
it/base/SessionCookieBaker.scala
it/pages/ChangeReturnFrequencyConfirmationISpec.scala
test/controllers/SignOutControllerSpec.scala
test/controllers/returnFrequency/ChangeReturnFrequencyConfirmationSpec.scala
test/controllers/returnFrequency/ConfirmVatDatesControllerSpec.scala

BTAT-7896 address deprecation warnings in vat-return-period-frontend

---

app/views/returnFrequency/confirm_dates.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala

[BTAT-8048] amended change link hidden text

---

conf/application.conf

BTAT-8120 - Updated assets frontend to 3.11.0

---

app/config/ServiceErrorHandler.scala
app/config/filters/ServiceFilters.scala
app/connectors/ContactPreferenceConnector.scala
app/connectors/VatSubscriptionConnector.scala
app/controllers/ChangeClientController.scala
app/controllers/LanguageController.scala
app/controllers/SignOutController.scala
app/controllers/predicates/AuthPredicate.scala
app/controllers/returnFrequency/ChangeReturnFrequencyConfirmation.scala
app/controllers/returnFrequency/ChooseDatesController.scala
app/controllers/returnFrequency/ConfirmVatDatesController.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
app/testOnly/views/StubAgentClientUnauth.scala.html
app/views/GovUkWrapper.scala.html
app/views/MainTemplate.scala.html
app/views/errors/UnauthorisedAgent.scala.html
app/views/errors/UnauthorisedNonAgent.scala.html
app/views/templates/ErrorTemplate.scala.html
app/views/templates/inputs/SingleCheckbox.scala.html
build.sbt
it/base/BaseISpec.scala
project/build.properties
project/plugins.sbt
test/controllers/predicates/AuthPredicateSpec.scala
test/mocks/MockHttp.scala
test/views/GovUkWrapperSpec.scala
test/views/errors/UnauthorisedAgentViewSpec.scala
test/views/errors/UnauthorisedNonAgentViewSpec.scala

[BTAT-8028] - sbt and scala upgrade

---

app/views/returnFrequency/ChangeReturnFrequencyConfirmation.scala.html
test/assets/messages/BaseMessages.scala
test/views/returnFrequency/ChangeReturnFrequencyConfirmationViewSpec.scala

[BTAT-8262] Fixed ChangeRetunrFrequencyConfirmation finish button

---

app/views/GovUkWrapper.scala.html
public/js/errorFocus.js

BTAT-8268 Fix focus error in error.js

---

it/base/SessionCookieBaker.scala
project/build.properties
project/plugins.sbt

BTAT-8316 Removed use of Auth SessionKeys from tests

---

app/views/returnFrequency/ChangeReturnFrequencyConfirmation.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala
test/views/returnFrequency/ChangeReturnFrequencyConfirmationViewSpec.scala

I have also removed some unused messages.

BTAT-8422 Added new paragraph to confirmation screen

---

app/views/returnFrequency/ChooseDates.scala.html
app/views/templates/inputs/RadioGroup.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala
test/views/returnFrequency/ChooseDatesViewSpec.scala
test/views/templates/inputs/RadioGroupTemplateSpec.scala

* [ x] Added Unit Tests for changed functionality
* [ x] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)

[BTAT-8420] Updated user guidance for stagger dates

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/GovUkWrapper.scala.html
conf/application.conf
test/mocks/MockConfig.scala

BTAT-8486 Updating GTM config

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/testOnly/views/StubAgentClientUnauth.scala.html
app/views/GovUkWrapper.scala.html
app/views/MainTemplate.scala.html
app/views/errors/UnauthorisedAgent.scala.html
app/views/errors/UnauthorisedNonAgent.scala.html
app/views/templates/ErrorTemplate.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
test/mocks/MockConfig.scala
test/views/GovUkWrapperSpec.scala
test/views/errors/UnauthorisedAgentViewSpec.scala
test/views/errors/UnauthorisedNonAgentViewSpec.scala

* [x ] Branch is rebased with master
* [x ] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)

[BTAT-8597] Started implementing updated GTM tracking consent script

---

app/models/circumstanceInfo/CustomerDetails.scala
it/stubs/VatSubscriptionStub.scala
test/assets/CircumstanceDetailsTestConstants.scala
test/assets/CustomerDetailsTestConstants.scala
test/models/circumstanceInfo/CustomerDetailsSpec.scala

BTAT-8917 add logic to deny certain party types

---

app/views/MainTemplate.scala.html
app/views/annualAccounting/PreventLeaveAnnualAccounting.scala.html
app/views/returnFrequency/ChooseDates.scala.html
conf/messages
conf/messages.cy
test/views/annualAccounting/PreventLeaveAnnualAccountingViewSpec.scala

BTAT-9390 move backlinks out of main template

---

app/assets/stylesheets/application.scss
app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/utils/ServiceUrl.scala
app/views/MainTemplate.scala.html
conf/application.conf
test/mocks/MockConfig.scala
test/utils/ServiceUrlSpec.scala
test/views/MainTemplateSpec.scala

[BTAT-9597] Added link to start page in service header

---

app/views/returnFrequency/ChooseDates.scala.html
test/views/returnFrequency/ChooseDatesViewSpec.scala

[BTAT-9543] Conditionally revealing content changed to hint text

---

conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala

[BTAT-9363] Add full stops to hint text

---

build.sbt
conf/application.conf

[BTAT-9645] Removed play-frontend-govuk

---

app/controllers/returnFrequency/ConfirmVatDatesController.scala
app/controllers/returnFrequency/ConfirmationController.scala
build.sbt
conf/app.routes
it/pages/ConfirmVatDatesControllerISpec.scala
it/pages/ConfirmationControllerISpec.scala
test/controllers/returnFrequency/ConfirmVatDatesControllerSpec.scala
test/controllers/returnFrequency/ConfirmationControllerSpec.scala

BTAT-9867 Removed user type suffix from confirmation page route

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/predicates/AuthPredicate.scala
app/views/errors/UserInsolventError.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/assets/messages/InsolventErrorMessages.scala
test/mocks/MockAuth.scala
test/mocks/MockConfig.scala
test/views/errors/UserInsolventErrorSpec.scala

[BTAT-9851] Added new error view for insolvent users

---

app/common/SessionKeys.scala
app/controllers/ChangeClientController.scala
app/controllers/predicates/AuthPredicate.scala
app/controllers/predicates/InFlightAnnualAccountingPredicate.scala
app/controllers/returnFrequency/ConfirmationController.scala
app/services/ReturnFrequencyService.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
build.sbt
it/pages/BasePageISpec.scala
it/pages/ConfirmVatDatesControllerISpec.scala
project/plugins.sbt
test/base/BaseSpec.scala
test/controllers/ChangeClientControllerSpec.scala
test/controllers/predicates/AuthPredicateSpec.scala
test/controllers/predicates/InFlightAnnualAccountingPredicateSpec.scala
test/controllers/returnFrequency/ChooseDatesControllerSpec.scala
test/controllers/returnFrequency/ConfirmVatDatesControllerSpec.scala

Btat 9917 Renamed session keys

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/MainTemplate.scala.html
build.sbt
conf/application.conf
test/mocks/MockConfig.scala

[BTAT-10013] Update config for new accessibility statement

---

app/views/returnFrequency/ConfirmDates.scala.html
test/views/returnFrequency/ConfirmDatesViewSpec.scala

BTAT-10139 Added double-click protection to CYA page button

---

app/audit/AuditService.scala
build.sbt
conf/application.conf
project/plugins.sbt

BTAT-10741 bootstrap update and auditing change

---

README.md
build.sbt
conf/application-json-logger.xml
it/base/SessionCookieBaker.scala
project/build.properties
project/plugins.sbt

[BTAT-10865] Upgraded dependencies

---

build.sbt
conf/application.conf

[BTAT-10916] Update container ID for GTM

---

README.md

[BTAT-11164] Update readme to refer to run.sh script

---

build.sbt
conf/messages.cy
project/plugins.sbt

BTAT-11302 Updated all instances of HMRC in Welsh translations

---

build.sbt

BTAT-11302 Deleted publish settings

---

app/connectors/VatSubscriptionConnector.scala
app/connectors/httpParsers/CircumstanceDetailsHttpParser.scala
app/connectors/httpParsers/ResponseHttpParsers.scala
app/connectors/httpParsers/SubscriptionUpdateHttpParser.scala
app/services/CustomerCircumstanceDetailsService.scala
app/services/ReturnFrequencyService.scala
it/connectors/VatSubscriptionConnectorISpec.scala
test/connectors/VatSubscriptionConnectorSpec.scala
test/mocks/connectors/MockSubscriptionConnector.scala
test/mocks/services/MockCustomerCircumstanceDetailsService.scala
test/mocks/services/MockReturnFrequencyService.scala
test/services/CustomerCircumstanceDetailsServiceSpec.scala
test/services/ReturnFrequencyServiceSpec.scala

BTAT-11375 Consolidated frontend HTTP parser type aliases

---

app/models/returnFrequency/ReturnPeriod.scala
build.sbt
project/plugins.sbt
test/models/returnFrequency/ReturnPeriodSpec.scala

BTAT-11431 Addressed compilation warnings

---

build.sbt

[BTAT-11590] Upgrading play-frontend-hmrc version
